### ISSUE TITLE
techpack/display/oplus is missing

### ISSUE THREAD

**Issue by libxzr** [OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8250#1]
SSIA

https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8250/blob/c1ef59b4d33506a1ac1d3696f17a9984d903af74/kernel/msm-4.19/techpack/display/.gitignore#L2

**Comment by ApexLegend007** [comment]
> SSIA
> 
> https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8250/blob/c1ef59b4d33506a1ac1d3696f17a9984d903af74/kernel/msm-4.19/techpack/display/.gitignore#L2

actually yes its missing i faced errors while compiling kernel about missing header files which are related to display itself @OnePlusOSSAdmin please look into it

**Comment by OnePlusOSSAdmin** [comment]
It’s been updated. Please check.

**Comment by libxzr** [comment]
Build passed and working confirmed. Thanks for the quick response.
